# Site settings
title:          Development blog
description:    "개발에 관련된 것을 정리하기 위한 블로그"
baseurl:        "/blog"
url:            "https://mertyn88.github.io"
remote_theme: chesterhow/tale

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         이준명
  url:          https://mertyn88.github.io
  email:        mertyn88@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-remote-theme
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         jekyll-tale
